### ISSUE TITLE
Remove L.Mixin.Events usage as it is deprecated

### ISSUE THREAD

**Issue by sommcz** [condense/react-leaflet-sidebarv2#1]
Hi,
sidebar with current Leaflet version show warning:
Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead.

Can you replace it, or may i help with a pull request? It is solved in the original sidebar js code.

Thank you
p.

**Comment by markhepburn** [comment]
Hi @sommcz , thanks for the report.

It's a slightly strange one; this plugin doesn't use Leaflet directly at all, just [react-leaflet](PaulLeCam/react-leaflet).  I'll definitely take PRs, or could you perhaps provide a minimal fiddle?

**Comment by sommcz** [comment]
it was just older version linked directly. my mistake.


btw i created a plunkr, if you want to create some example based on it (http://plnkr.co/edit/l7HjxD)

**Comment by markhepburn** [comment]
Aah, fair enough, cheers.

Thanks for the plunkr!  I think it might be missing the leaflet css?  (the tiles were rendering a bit funny for me).  Let me know if you have any other issues.
