### ISSUE TITLE
Sidebar is created outside map div

### ISSUE THREAD

**Issue by ryazhang** [condense/react-leaflet-sidebarv2#4]
![qq 20180627111303](https://user-images.githubusercontent.com/33251407/41950992-5b6772de-79fb-11e8-9e50-27851b4bb028.png)

I am using react-leaflet-sidebarv2 with your example.
But I found that sidebar located outside of map div.
Could you please have a look at this and help me to solve this problem?

**Comment by markhepburn** [comment]
Hi @ryazhang , hard to say without seeing your example.
A few things to check, per the README:
* Do you have the leaflet-sidebar-v2 CSS included?
* Is the <Sidebar> _before_ the <Map>?
* Does the Map have a "sidebar-map" class?

**Comment by markhepburn** [comment]
I'll close this one off; feel free to re-open if you can provide more information (a [js-fiddle](https://jsfiddle.net/) that reproduced the problem would be great)
