### ISSUE TITLE
TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by Josic0** [condense/react-leaflet-sidebarv2#48]
This is code I´ve added in the project as given example:
![code](https://user-images.githubusercontent.com/42252730/142890655-c2f07c3d-a660-41b4-8de8-4be7776ad28b.png)

However, the plugin is not working as espected. I get this output...
![error](https://user-images.githubusercontent.com/42252730/142890883-93e5570f-4ec9-4bff-aebf-886a0cf06783.png)

Any idea what is happening?

Thank you in advance.

**Comment by markhepburn** [comment]
I don't, sorry!  (I haven't used this repo in several years).  There's plenty of similar reports around, but they seem to imply an issue in the import, eg component instead of Component; have you verified that react is installed correctly?

**Comment by Josic0** [comment]
I´ll check it out. I´ll post any solution I find on here.

**Comment by Josic0** [comment]
I have come up with a solution. The plugin was built on react-leafletV1.6.4 (current V 3.2.2) , so I have had to downgrade the react-leaflet version to make it work.

**Comment by markhepburn** [comment]
I'm glad you found a work-around -- thanks very much for documenting it here in case others come across the same!
