### ISSUE TITLE
[Question] Use without leaflet?

### ISSUE THREAD

**Issue by danZib** [condense/react-leaflet-sidebarv2#5]
I know that this doesn't really belong here, please excuse me already but I was hoping to receive some recommendation from a more experienced developer.

I'm working on a SVG floor plan viewer, that is not (yet) using leaflet. I integrated my own simple sidebar at the moment but the sidebar here would be just such  perfect fit.

It seems like a stupid question, but is there an easy way to use it without the integration of leaflet or is my simple sidebar and gradually updating it the better way to go?

Again sorry for the inappropriate question but some advice would help me a lot.

**Comment by markhepburn** [comment]
Hi @danZib -- I don't see any reason why not.  All this project does is render React markup; the CSS is from https://github.com/nickpeihl/leaflet-sidebar-v2.  I'm not a CSS expert, but I can't see why you couldn't rejig that (or just give your floor-play div a .sidebar-map class, and whatever else is necessary)
