### ISSUE TITLE
Failed prop type

### ISSUE THREAD

**Issue by Masoumeh** [condense/react-leaflet-sidebarv2#6]
When I use the example to produce both sidebar and map, it seems the side bar doesn't load properly and the style is not loaded correctly. It's fill width and all the tabs are active! I also get the following error in the web console: 
```
Warning: Failed prop type: The prop `closeIcon` is marked as required in `Sidebar`, but its value is `undefined`.
    in Sidebar (created by App)
    in App
```
Here is the App component:

```
export default class App extends Component {

    constructor(props) {
        super(props);
        this.state = {
            collapsed: false,
            selected: 'home',

            zoom:   [4], // map zoom
            center: [30, 33],
            containerStyle: {
                height: "100vh",
                width: "100vw"
            },
            // places: EMPTY_GEOM, // Places GeoJSON
            // routes: EMPTY_GEOM, // Routes GeoJSON
            highlighted: { // Selected route (if any) - places & route segments
                places:   [],
                segments: []
            }
        }
    }
    onClose() {
        this.setState({collapsed: true});
    }
    onOpen(id) {
        this.setState({
            collapsed: false,
            selected: id,
        })
    }

    render() {
        return (
            <div>
                <Sidebar id="sidebar" collapsed={this.state.collapsed} selected={this.state.selected}
                         onOpen={this.onOpen.bind(this)} onClose={this.onClose.bind(this)}>
                    <Tab id="home" header="Home" icon="fa fa-home">
                        <p>No place like home!</p>
                    </Tab>
                    <Tab id="settings" header="Settings" icon="fa fa-cog" anchor="bottom">
                        <p>Settings dialogue.</p>
                    </Tab>
                </Sidebar>
                <Map className="sidebar-map"
                    center={this.state.center}
                    zoom={this.state.zoom}
                >
                    <TileLayer
                        // attribution={stamenTonerAttr}
                        url={stamenTonerTiles}
                    />
                </Map>
            </div>
        );
    }
}
```
Could you please give me a clue why this is happening and how I can resolve it?

Thanks!

**Comment by markhepburn** [comment]
Hi @Masoumeh , thanks for your report.

Are you including the sidebar css?  I don't provide that; that's from the upstream project https://github.com/nickpeihl/leaflet-sidebar-v2, or you can use a CDN link like https://unpkg.com/leaflet-sidebar-v2@3.0.2/css/leaflet-sidebar.min.css  From the sounds of it that's most likely what you're seeing.

The warning is something I've overlooked, thanks for that (it is indeed marked as required!  I'll push up a fix when I have time)

**Comment by Masoumeh** [comment]
Hi @markhepburn,

Thanks for the explanation. I still couldn't make it work though. Seems I got some other bugs from Webpack! I will keep you posted if something else come up regarding the leaflet sidebar.

And, I hope you get the chance to fix the warning as soon as possible. I really need to use it. Looking forward!

Thanks!

**Comment by Masoumeh** [comment]
That's right. The icon shouldn't be the issue and css might just resolve my problem. But, I couldn't get it yet since I got another stupid error from webpack (Module not found!) after including css. I'm new in reactjs and still trying to know my way around it.

**Comment by markhepburn** [comment]
Hi @Masoumeh -- I think I'll close this one (the close icon is required, although can technically be ignored).  If you think it should be optional you can always open a ticket for that.

**Comment by Masoumeh** [comment]
Thank you so much dear Mark.

All best,
Masoumeh

**Comment by designbyadrian** [comment]
It's not clear in the readme that the `closeIcon` is a prop that your component requires.
