### ISSUE TITLE
leaflet-sidebarv2 autopan functionality

### ISSUE THREAD

**Issue by WilliamTheMarsman** [condense/react-leaflet-sidebarv2#7]
Is it possible to leverage leaflet-sidebarv2 autopan functionality with this library? As seen in the gif found in the [readme for leaflet-sidebarv2](https://github.com/nickpeihl/leaflet-sidebar-v2)?

In leaflet-sidebarv2 this was done as follows:

```
 Leaflet.control.sidebar({ autopan: true }) // makes sure that the map center always stays visible. 
```
Thank you for creating this leaflet react plugin.

**Comment by markhepburn** [comment]
Hi @WilliamTheMarsman , thanks for the suggestion.  Shooting from the hip, I suspect this is better handled above the plugin itself, by hooking into the onOpen/Close events, which is basically what leaflet-sidebar does [by the looks of it](https://github.com/nickpeihl/leaflet-sidebar-v2/commit/d03a203a46b570db3a8044921b7c7e9a11e7ad31#diff-c56a637f047fd5f3ef8bf1b00d8ab013R446).

This plugin doesn't actually know anything about your map itself, it's purely rendering markup.  Let me know if you have any thoughts though!

**Comment by markhepburn** [comment]
Hi @WilliamTheMarsman -- any objections to me closing this?
